### ISSUE TITLE
entrypoint.sh: 2: set: Illegal option - 

### ISSUE THREAD

**Issue by LMADoneur** [StiviiK/ragemp#5]
I tried running the dockerfile and i get this error.

`entrypoint.sh: 2: set: Illegal option -`

**Comment by StiviiK** [comment]
Could you please provide more Information?
- Host OS, Docker Environment
- Did you try to building the Image yourself or pulling from Docker Hub?
- If you build it yourself, what was the command you are using?
- What was the command you used to run the Image?

**Comment by LMADoneur** [comment]
Debian, pulling from dockerhub
entrypoint.sh from github
```
docker run \
  -p 22005:22005/udp \
  -p 22006:22006 \
  -d \
  --name ragemp-server \
  stivik/ragemp

```

**Comment by StiviiK** [comment]
It seems something is wrong with the docker hub image, i'll look into it.

**Comment by StiviiK** [comment]
There was an encoding issue, this should be fixed now, please verify.

**Comment by LMADoneur** [comment]
Working well, thank you !
